### ISSUE TITLE
Documentation / Example on using alternate tenant from config.yaml

### ISSUE THREAD

**Issue by rob-buskens-sp** [sailpoint-oss/powershell-sdk#9]
The config.yaml supports multiple tenants.
Using the activeenvironment is straight forward.
Overriding with environment variables is a great open, particularly in production environments.
Not sure how one gets a configuration other than the activeenvironment
Or is this a limitation of the config.yaml? seems undesirable to only have one tenant active at a time (for the SDK uses, maybe it's fine for the SaaS Connector uses).

**Comment by tyler-mairose-sp** [comment]
Hello @rob-buskens-sp,

This is an example of multiple tenants in your config.yaml. You can switch environments by changing the `activeenvironment` variable between tenant names in your environments key. The PowerShell SDK will check to see if your activeenvironment has changed and will update the API calls accordingly.

```yaml
activeenvironment: devrel # the key that identifies the currently active environment
authtype: pat # currently only pat and pipeline are supported if the ENV VAR SAIL_AUTH_TYPE is configured to "pipeline" it will override this value
customexporttemplatespath: "" # the path to the users custom export templates file if one is provided
customsearchtemplatespath: "" # the path to the users custom search templates file if one is provided
debug: false # the debug setting  
environments: # the configured environments 
  devrel:
    baseurl: https://devrel.api.identitynow.com
    pat:
      accesstoken: example-access-token
      clientid: g0567b766b413b22c05c66e75d532f1b
      clientsecret: cabd0e950a7230b63c1ff45be33fb22065b382b6251a73c61177a8bb5482fcc7
      expiry: example-access-token-expiry
    tenanturl: https://devrel.identitynow.com
  ps-training3:
    baseurl: https://ps-training3.api.identitynow.com
    pat:
      accesstoken: example-access-token
      clientid: g0567b766b413b22c05c66e75d532f1b
      clientsecret: cabd0e950a7230b63c1ff45be33fb22065b382b6251a73c61177a8bb5482fcc7
      expiry: example-access-token-expiry
    tenanturl: https://ps-training3.identitynow.com
```
